version: "3.9"
name: fastapi-mongo-crud-example

services:
  app:
    container_name: app
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .docker.env
