services:
  app:
    labels:
    - traefik.enable=true
    - traefik.http.routers.fastapi-crud-example.rule=Host(`${DOMAIN_NAME?}`)
    - traefik.http.routers.fastapi-crud-example.tls=true
    - traefik.http.routers.fastapi-crud-example.entrypoints=websecure
    networks:
      - traefik-public
      - default

networks:
  traefik-public:
    external: true

  default:
