version: "3.9"
name: fastapi-mongo-crud-example

services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
      target: PROD
    environment:
      MONGO_URI: ${MONGO_URI:?}
      SQLALCHEMY_DATABASE_URL: ${SQLALCHEMY_DATABASE_URL:?}
    command: "uvicorn src.main:app --host 0.0.0.0 --port 8000"
