version: "3.9"
name: fastapi-mongo-crud-example

services:
  app:
    build:
      target: DEV
    ports:
      - "8000:8000"
    volumes:
      - ../src:/app/src
    command: "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
